//
// Created by philipp on 21.12.17.
//

#ifndef EXCHANGABLETRANSPORTS_OPTIMISTICRDMATRANSPORT_H
#define EXCHANGABLETRANSPORTS_OPTIMISTICRDMATRANSPORT_H



class OptimisticRdmaTransport {

};



#endif //EXCHANGABLETRANSPORTS_OPTIMISTICRDMATRANSPORT_H
